{ pkgs ? import <nixpkgs> {} }:
rec {
    generateSrcFromSpec = { specification, generatorName, srcOverrides ? { ... }: {} } :
        let
            default-src = {
                #inherit attrs;

                name = "${generatorName}-openapi-generated-source";
                # vesion = "0.1"; # TODO
                nativeBuildInputs = with pkgs; [ openapi-generator-cli ];

                buildPhase = ''
                    ${pkgs.openapi-generator-cli}/bin/openapi-generator-cli generate -i ${specification} -g ${generatorName}
                '';

                installPhase = ''
                    cp -r . $out
                '';

                dontUnpack = true;
            };
        in
            pkgs.stdenv.mkDerivation (default-src // srcOverrides default-src);

    createGenerator = { generatorName, dontBuildBinaryReason ? null, binaryOverrides ? { ... }: {}, binaryBuilder ? pkgs.stdenv.mkDerivation, srcOverrides ? { ... }: {}, ... } : { specification } :
        let
            generated-src = generateSrcFromSpec {
                inherit specification generatorName srcOverrides;
            };
            default-binary = {
                name = "${generatorName}-openapi-generated-lib";
                src = generated-src;
            };
        in
        rec {
            inherit generated-src generatorName dontBuildBinaryReason;
            binary =
                if dontBuildBinaryReason == null then
                    binaryBuilder (default-binary // (binaryOverrides default-binary))
                else
                    throw ''
                        The "${generatorName}" OpenAPI generator doesn't support building binaries from source generated by the generator.

                        Explanation why "${generatorName}" doesn't support building:
                          ${builtins.replaceStrings ["\n"] ["\n  "] dontBuildBinaryReason }
                    '';
        };

    createGeneratorsSet = generators:
        (builtins.mapAttrs
            (name: value: createGenerator (
                value // {
                    generatorName = name;
                }
            )))
            generators;

    generators = createGeneratorsSet
        (builtins.mapAttrs
            (name: fs_item_type: import (./. + ("/generators/" + name)) { inherit pkgs; })
            (pkgs.lib.attrsets.filterAttrs
                (name: fs_item_type: fs_item_type == "directory")
                (builtins.readDir ./generators)));
}
